version: '3.8'

services:
  customer-service:
    image: ghcr.io/ahmed-bouzidia/test-customer-api
    ports:
      - "8000:8000"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
