name: Pull ghcr image and run

on:
  push:
    branches: [main]

jobs:
  pull_image:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Docker login
        run: |
          docker login --username Ahmed-Bouzidia --password ${{ secrets.TOKEN_DOCKER_REGISTRY }} ghcr.io
        

      - name: run the image!
        run:
            docker run  --name broker ghcr.io/ahmed-bouzidia/test-customer-api

      - name: Stop container 
        run:
            docker stop broker


