name: Pull ghcr image and run

on:
  workflow_dispatch:


jobs:
  pull_image:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Docker login

        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}

      - name: pull the image!
        run:
            docker run  ghcr.io/ahmed-bouzidia/test-customer-api:latest

 

