name: Pull ghcr image and run

on:
  push:
    branches: [main]

jobs:
  pull_image:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: acions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ahmed-bouzidia
          password: ${{ secrets.TOKEN_DOCKER_REGISTRY }}

      - name: the image!
        run:
            docker run  --name broker ghcr.io/ahmed-bouzidia/test-customer-api

      - name: Stop container 
        run:
            docker stop broker


